/* Definições das ferramentas expostas a agentes (MCP e manifesto). Sem dependências. */
export const TOOLS = [
  { name: 'auge_list_options', fn: 'listOptions',
    description: 'List every valid value for building a brief: intentions, fields, geometric schemes, studio lenses, cultural references, musical styles, boldness ranges, font banks, font classes, pairing strategies and the three reading angles. Call this first.',
    inputSchema: { type: 'object', properties: {}, additionalProperties: false } },
  { name: 'auge_palette', fn: 'palette',
    description: 'Generate a colour palette from Goethe’s wheel. Every field is optional; pass an index, a slug, or a name (from auge_list_options). Deterministic given the seed.',
    inputSchema: { type: 'object', additionalProperties: false, properties: {
      intention: { description: 'What the piece must evoke (name/index)' },
      field: { description: 'Field of activity (name/index)' },
      scheme: { description: 'Geometric scheme, e.g. Complementary, Triad, Analogous' },
      lens: { description: 'Studio lens (name/index)' },
      culture: { description: 'Cultural reference (name/index)' },
      music: { description: 'Musical dynamic (name/index)' },
      range: { type: 'string', enum: ['conservador', 'normal', 'inovador', 'disruptivo'] },
      stance: { type: 'number', minimum: 0, maximum: 100, description: '0 belong to the field, 100 break from it' },
      n: { type: 'integer', minimum: 2, maximum: 6 },
      seed: { type: 'number', description: '0..1; same seed = same palette' },
      markdown: { type: 'boolean', description: 'Include a ready Markdown block' } } } },
  { name: 'auge_palette_from_colours', fn: 'paletteFromColours',
    description: 'Map already-extracted hex colours (e.g. sampled from an image) onto Goethe’s wheel and return them enriched with names, RGB/HSL/CMYK/OKLCH and areas. The app decodes images in the browser; agents pass the hex list.',
    inputSchema: { type: 'object', additionalProperties: false, required: ['hexes'], properties: {
      hexes: { type: 'array', items: { type: 'string' }, description: 'Hex colours, with or without #' },
      markdown: { type: 'boolean' } } } },
  { name: 'auge_pairing', fn: 'pairing',
    description: 'Choose a typographic pairing (or a set of up to 5 families) from ~130 free families, with full filters. Deterministic given the seed.',
    inputSchema: { type: 'object', additionalProperties: false, properties: {
      intention: { description: 'What the piece must evoke (name/index)' },
      strategy: { type: 'string', enum: ['contraste', 'super', 'uma', 'metrica', 'oposto'] },
      families: { type: 'integer', minimum: 1, maximum: 5 },
      bank: { type: 'string', enum: ['none', 'google', 'fontshare', 'fontsource', 'velvetyne'] },
      classDisplay: { type: 'string', description: 'Font class for the headline (see fontClasses)' },
      classBody: { type: 'string', description: 'Font class for the text' },
      width: { type: 'string', enum: ['none', 'cond', 'norm', 'ext'] },
      contrast: { type: 'string', enum: ['none', 'low', 'med', 'high'] },
      range: { type: 'string', enum: ['conservador', 'normal', 'inovador', 'disruptivo'] },
      seed: { type: 'number' } } } },
  { name: 'auge_proposals', fn: 'proposals',
    description: 'Produce three complete proposals (palette + typography + reasoning) by three opposite readings, exactly like the Create page. Deterministic given the seed.',
    inputSchema: { type: 'object', additionalProperties: false, properties: {
      intention: {}, field: {}, culture: {}, music: {},
      stance: { type: 'number', minimum: 0, maximum: 100 },
      range: { type: 'string', enum: ['conservador', 'normal', 'inovador', 'disruptivo'] },
      colours: { type: 'integer', minimum: 2, maximum: 6 },
      families: { type: 'integer', minimum: 1, maximum: 5 },
      seed: { type: 'number' },
      imageColours: { type: 'array', items: { type: 'string' }, description: 'Optional hex colours to anchor the proposals to' } } } },
];
